# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "4"

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

git:
  submodules: false

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm install

# http://docs.travis-ci.com/user/build-lifecycle/
before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

# http://docs.travis-ci.com/user/pull-requests/
script:
  - neon build
  - mv native/index.node dist/linux/x64
  - npm test

notifications:
  email: false

branches:
  only:
    - master

